export enum RandomBooksTypes {
	RANDOM_BOOKS_REQUESTED = 'RANDOM_BOOKS_REQUESTED',
	RANDOM_BOOKS_REQUEST_SUCCESS = 'RANDOM_BOOKS_REQUEST_SUCCESS',
	RANDOM_BOOKS_REQUEST_FAILURE = 'RANDOM_BOOKS_REQUEST_FAILURE',
};